### ISSUE TITLE
Junk data

### ISSUE THREAD

**Issue by reflechant** [mbk-dev/okama#13]
When loading certain assets it shows false data.
`assets = ok.AssetList(["VTBA.MOEX", "VTBH.MOEX", "SBGB.MOEX"])
assets.wealth_indexes`

The result is this:

`
	VTBA.MOEX	VTBH.MOEX	SBGB.MOEX	USD.INFL

2021-04	1369.766402	1062.898065	946.963297	1040.959324
2021-05	137.244019	106.279943	966.626194	1049.286999
2021-06	140.203804	107.462560	9.702027	1059.045368
2021-07	143.120043	107.870918	9.866962	1064.128786
2021-08	148.166985	108.334191	9.850195	1066.363456`

Data starting from 2021-06 is junk - those assets did not drop 100 times.
Looks like a bug with formatting/floating point/type conversion.

**Comment by chilango74** [comment]
Many funds in MOEX had a 1:100 split in may. This infromtaion is not added to adjusted close. We will correct it soon.

Here is the information about splits in MOEX:
[https://iss.moex.com/iss/statistics/engines/stock/splits](https://iss.moex.com/iss/statistics/engines/stock/splits)
