### ISSUE TITLE
Integrating Tinkoff-etna into the prediction of the asset price

### ISSUE THREAD

**Issue by nencoru** [mbk-dev/okama#15]
Hello there! There was recently a release from Tinkoff of their first framework to work with time-series prediction called ETNA.

I wonder, would it be suitable to integrate their solution into okama in order to lay next to the  Monte-Carlo prediction model?

Link to the framework: https://github.com/tinkoff-ai/etna

**Comment by chilango74** [comment]
Thans for suggestion. I'm not familiar with ETNA but will try it.

In any case it's easy to use any time-series prediction engine with okama historical data: 

- [Portfolio.close_monthly](https://okama.readthedocs.io/en/master/stubs/okama.Portfolio.close_monthly.html) 
- [Asset.close_monthly](https://okama.readthedocs.io/en/master/stubs/okama.Asset.close_monthly.html)

**Comment by nencoru** [comment]
Yeah, I saw those properties in order. However, the question was about adding ETNA next to `plot_forecast` / `plot_forecast_monte_carlo` in order to get the predictions based on the historical data. 
Of course, it could demand either having a great video card, or a pre-trained model in order to predict such things, but it could significantly improve the prediction of the price.
So the question is is it suitable to integrate it with that framework, or it's better to keep it separated?

**Comment by chilango74** [comment]
@nencoru  thanks for explanation. I've explored in more details ETNA package. It looks like a good forecasting engine. 
However, I don't think it can be integrated in okama for several reasons:
- okama intentented to be a lightweight package with few dependencies and no hardware requirements
- in our model currently, we don't predict a price. We work with rate of return distributions which is more probabilistic concept. 

Integration of such engines as ETNA can be interesting in the future but it will require substantial change in the package. It’s not in our Roadmap yet.

**Comment by nencoru** [comment]
> @nencoru  thanks for explanation. I've explored in more details ETNA package. It looks like a good forecasting engine. 
> However, I don't think it can be integrated in okama for several reasons:
> - okama intentented to be a lightweight package with few dependencies and no hardware requirements
> - in our model currently, we don't predict a price. We work with rate of return distributions which is more probabilistic concept. 
> 
> Integration of such engines as ETNA can be interesting in the future but it will require substantial changes in the package. It’s not in our Roadmap yet.

I see, well okay then.
Closing issue.
