### ISSUE TITLE
Check when an FX rate first_date limits an Asset_List or Portfolio historical data range

### ISSUE THREAD

**Issue by chilango74** [mbk-dev/okama#17]
![image](https://user-images.githubusercontent.com/29829921/147054578-68b8bba9-9d18-4954-8715-e0d6a235e86c.png)
Historical period length is 15 years.
However, `NSEI.INDX' has over 30 years of history:
![image](https://user-images.githubusercontent.com/29829921/147054720-78afe050-8e83-4b86-b537-d9de096159e5.png)

The first_date is taken from `INRUSD.FX`.

**Comment by nenkoru** [comment]
Could you please elaborate a little bit please on this issue?
As I have taken a look INR-USD data is limited by 18 years by the API of Okama. However, I even struggled to find data for INR-USD on the internet!
Was able to find only this one https://fred.stlouisfed.org/series/DEXINUS

**Comment by chilango74** [comment]
In the example above `first_date` of AssetList is not correct. It can't be 1990 when `period_length` is 15 ears.
Here the problem is more general and not depending on INRUSD only. There are rare situation when the `period_length` of AssetList or Portfolio is limited  by one of the currencies. Usually assets limit it. 
[ListMaker._make_list](https://github.com/mbk-dev/okama/blob/1e202bc801aea8adaf4c2ad033cd51af0c957df5/okama/common/make_asset_list.py#L104) should check FX first_date also when [adjusting to the base currency](https://github.com/mbk-dev/okama/blob/1e202bc801aea8adaf4c2ad033cd51af0c957df5/okama/common/make_asset_list.py#L170).

**Comment by nenkoru** [comment]
> In the example above `first_date` of AssetList is not correct. It can't be 1990 when `period_length` is 15 years. Here the problem is more general and not depending on INRUSD only. There are rare situations when the `period_length` of AssetList or Portfolio is limited by one of the currencies. Usually assets limit it. [ListMaker._make_list](https://github.com/mbk-dev/okama/blob/1e202bc801aea8adaf4c2ad033cd51af0c957df5/okama/common/make_asset_list.py#L104) should check FX first_date also when [adjusting to the base currency](https://github.com/mbk-dev/okama/blob/1e202bc801aea8adaf4c2ad033cd51af0c957df5/okama/common/make_asset_list.py#L170).

I still do not understand fully the idea behind this. What's the expected behavior?

**Comment by chilango74** [comment]
`period_length` is the difference between the `first_date` and `last_date`. If you check the example above `period_length` is 15 years and 11 months. However, the `first_date` is 1990-08 and the `last_date` is 2021-11. The parameter `first_date` is not correct here. 

What is happening...
When Portfolio or AssetList is initiated, we download several historical data series:
-	assets
-	inflation
-	base currency
-	FX currency pairs to adjust 
first_date of the AssetList is the latest first_date of the mentioned time series. `last_date` is the `newest last_date`. It should work this way, but for some reason I forgot to include **FX currency rates** used in  [_adjust_ror_to_currency](https://github.com/mbk-dev/okama/blob/1e202bc801aea8adaf4c2ad033cd51af0c957df5/okama/common/make_asset_list.py#L170) in this comparison: 
```
first_dates_sorted: list = sorted(first_dates.items(), key=lambda y: y[1])
last_dates_sorted: list = sorted(last_dates.items(), key=lambda y: y[1])
```
In the example above the first_date should consider the INRUSD.FX historical data depth.

**Comment by chilango74** [comment]
Resolved by https://github.com/mbk-dev/okama/commit/d3c01744aa53e726375555217a32217ea450d1e4
