### ISSUE TITLE
Replace Pandas .append() with .concat()

### ISSUE THREAD

**Issue by chilango74** [mbk-dev/okama#31]
The frame.append method is deprecated and will be removed from pandas in a future version.

**Comment by Aadityajoshi151** [comment]
I would like to work on this. Can you please assign this?
Thanks.

**Comment by chilango74** [comment]
Closed with  [fix #3: replace .append (deprecated) with .concat](https://github.com/mbk-dev/okama/commit/2ab6074f07ba836913f89ac148b38a6970c881fc)
