### ISSUE TITLE
No module named 'okama.api'

### ISSUE THREAD

**Issue by dknugo** [mbk-dev/okama#5]
Начиная с версии 0.93, импорт библиотеки завершается с ошибкой:
ModuleNotFoundError: No module named 'okama.api'

**Comment by chilango74** [comment]
В версии 0.95 эта ошибка устранена ... обновите библиотеку и дайте знать, если проблема все еще остается.

**Comment by dknugo** [comment]
К сожалению, ошибка осталась. В версиях 0.93 и 0.95

**Comment by chilango74** [comment]
Дайте пожалуйста полный скриншот ошибки, а так же сообщите версию Python. У меня не получилось воспроизвести...

**Comment by dknugo** [comment]
Версия 3.8
![2021-01-26_16-17-33](https://user-images.githubusercontent.com/18755758/105850335-a763ec00-5ff2-11eb-9cac-9764c14b65ec.jpg)

**Comment by chilango74** [comment]
Спасибо. Удалось воспроизвести. Ошибка возникает именно при импорте через Jpyter. В том же окружении при импорте через ipython или командную строку python всё работает. Будем разбираться ...

**Comment by chilango74** [comment]
Исправил setup.py. Проблема была в отсутствии find_packages() поэтому билд происходил неправильно и PyPi содержал некорректную версию библиотеки. 
В версии 0.97 ошибка исправлена.
