### ISSUE TITLE
Tickers with dot "." 

### ISSUE THREAD

**Issue by chilango74** [mbk-dev/okama#50]
Tickers with dots in name like `BRK.A` can't be used.
![image](https://user-images.githubusercontent.com/29829921/200113122-10eda207-e5b6-419e-adf3-6c9ec02f944f.png)

**Comment by devbazregari** [comment]
hi buddy. i hope you're doing great. I want to give this issue a try if you let me.

**Comment by Yack333** [comment]
Hey chilango, from what I've found the issue is not with the ticker having a dot but that specific suffix isn't actually correct for this asset. The ok.asset() works for SPY.US and in this case i'm assuming by BRK.A you mean the Berkshire Hathaway Inc Class A. Which for this asset the ticker is BRK-A.US and this does indeed work with the ok.asset() function. Seeing as a lot of assets are spelled differently online it could be helpful to return a check on the database to see what the user meant by his input as some assets will have dots where dashes should be and vice versa.

**Comment by chilango74** [comment]
> Hey chilango, from what I've found the issue is not with the ticker having a dot but that specific suffix isn't actually correct for this asset. The ok.asset() works for SPY.US and in this case i'm assuming by BRK.A you mean the Berkshire Hathaway Inc Class A. Which for this asset the ticker is BRK-A.US and this does indeed work with the ok.asset() function. Seeing as a lot of assets are spelled differently online it could be helpful to return a check on the database to see what the user meant by his input as some assets will have dots where dashes should be and vice versa.

Actually my example was not correct. One should request `BRK.A.US`:
![image](https://user-images.githubusercontent.com/29829921/200158579-afabff5e-489e-4775-8242-4532948388ca.png)
But the bug still remains.

**Comment by chilango74** [comment]
> hi buddy. i hope you're doing great. I want to give this issue a try if you let me.

Sure. It should not be defficult. The problem is how `namespace` defined: https://github.com/mbk-dev/okama/blob/2c8d577f55c07a2e16fe1f464a369acf41223456/okama/asset.py#L52

**Comment by devbazregari** [comment]
bro, I'm not quite sure about what you want. do you want this "BRK.A" to be acceptable?  in another word when we enter " BRK.A " this must be "BRK.A" not anything else. it's right?

**Comment by chilango74** [comment]
> @chilango74 bro, I'm not quite sure about what you want. do you want this "BRK.A" to be acceptable? in another word when we enter " BRK.A " this must be "BRK.A" not anything else. it's right?

Our database uses **namespaces** to identify stock markets. To get the information about US ticker BRK.A one must use it with US namespace. The complete symbol is `BRK.A.US` (BRK.A is a ticker, US - namespace). Now the package does not correctly identify the namespace if the symbol has more than one dot in request. 

The correct definition of Namespace - the combination of symbols after the LAST dot.
