### ISSUE TITLE
avoid running the module namespaces.py when importing okama

### ISSUE THREAD

**Issue by chilango74** [mbk-dev/okama#52]
`__init__.py` has imports from `namespaces.py` which forces http request to API during `import okama`.

Redefine as functions following:
```
namespaces = get_namespaces()
assets_namespaces = get_assets_namespaces()
macro_namespaces = get_macro_namespaces()\
```

**Comment by agarwal-aryan** [comment]
Sir/Madam 
What you want us to do here. Please tell because I want to be a new contributor to the project.

**Comment by chilango74** [comment]
> Sir/Madam What you want us to do here? Please tell because I want to be a new contributor to the project.

Hi. Thanks for yopur interest. Well the issue is simple. `namespace` is a shortcut to the function `get_namespaces()`. The function is run on import which is not good. `namespace` should be redefine with class property or function. Static class property is better as it will work without brackets.

**Comment by agarwal-aryan** [comment]
According to my understanding,

You want us to change the occurrence of **namespaces** to **get_namespaces()** and other also
Am i right?

**Comment by chilango74** [comment]
> You want us to change the occurrence of **namespaces** to **get_namespaces()** and other functions also. Am i right?

It's not a good idea use `get_namespaces()` as this function has no arguments. It's looks like we should use **module properties** to call this function without brackets:
[https://stackoverflow.com/questions/880530/can-modules-have-properties-the-same-way-that-objects-can](https://stackoverflow.com/questions/880530/can-modules-have-properties-the-same-way-that-objects-can)

**Comment by agarwal-aryan** [comment]
Sorry I am not able to understand the problem even from the stackoverflow link .

**Comment by chilango74** [comment]
> Sorry I am not able to understand the problem even from the stackoverflow link .

.. not a problem. This issue seems to be more difficult than I expected.

**Comment by chilango74** [comment]
Resolved with https://github.com/mbk-dev/okama/commit/ac92bd698d0020ce5ca599d03a30b9d5e619cb79
