### ISSUE TITLE
Rename cagr argument in plot_transition_map() with x_axe

### ISSUE THREAD

**Issue by chilango74** [mbk-dev/okama#54]
Rename `cagr` argument in [`plot_transition_map()`](https://github.com/mbk-dev/okama/blob/2c8d577f55c07a2e16fe1f464a369acf41223456/okama/frontier/single_period.py#L889) with more informative `x_axe`.
Default value should be "risk":
`x_axe: str = 'risk'`

Only two values are allowed: "cagr" and "risk".

**Comment by Mathii0402** [comment]
Ok I can solve this.

**Comment by chilango74** [comment]
@Mathii0402 ok. Thank you!

**Comment by Mathii0402** [comment]
Sorry I tried solving this and made a PR but the PR was closed. I don't know why

**Comment by chilango74** [comment]
@Mathii0402 it looks like you have deleted it in your repository ...
![image](https://user-images.githubusercontent.com/29829921/226834404-3b54bd56-9652-4ff7-b9a9-84c15a80f09f.png)

**Comment by Mathii0402** [comment]
Ok I'll again fork and make a PR after making changes

**Comment by chilango74** [comment]
Thank you. Accepted.
