### ISSUE TITLE
index_rolling_corr error

### ISSUE THREAD

**Issue by dknugo** [mbk-dev/okama#6]
При вызове AssetList.index_rolling_corr ошибка:
TypeError: check_rolling_window() missing 1 required positional argument: 'ror'

**Comment by chilango74** [comment]
Спасибо. Будет исправлено в следующем коммите.

**Comment by chilango74** [comment]
В ветке master ошибка исправлена. Через pip работающая версия будет доступна в следующем релизе (версия 0.98).
