### ISSUE TITLE
Library not fetching new data

### ISSUE THREAD

**Issue by PineTreePizza** [mbk-dev/okama#63]
Recently I started writing a telegram bot using this library for getting stock data, yesterday it worked just fine but today the data is not updating, what is the cause of this? The data is way past 20 minutes old, I've checked TradingView for the ticker that I use and it seems that the ticker data hasn't updated from yesterday.
(RU) Здравствуйте, недавно я начал писать бота в телеграмм с этой библиотекой, и со вчеращнего вечера я заметил что акции не изменяются, что может быть причиной этого и часто ли так проиходит, а то хотелось бы стабильности в такой хорошей библиотеке как эта.

**Comment by PineTreePizza** [comment]
From what I see the live fetching of stocks doesnt work for moex stocks, is this true?

**Comment by chilango74** [comment]
> From what I see the live fetching of stocks doesnt work for moex stocks, is this true?

Hi. We are receiving price data from 3d parties and not able to control whether it is delayed correctly or not. 

Okama database and package works alot with end of month close data and adjusted close. This is the main type of data. The end of day and live prices are not used in our calculations. It's kind of a free bonus. So you shoud use this information at your risk.

**Comment by chilango74** [comment]
Thinking it over... we use caching in the API. It may affect the live prices. I'll check and let you know if it can be corrected this way.

**Comment by PineTreePizza** [comment]
> Thinking it over... we use caching in the API. It may affect the live prices. I'll check and let you know if it can be corrected this way.

Well, I've been having a problem of the prices not changing for like 2 days already, just checked again. If you want to test the ones I do are SBER.MOEX, LKOH.MOEX, AAPL.US. before yesterday they were changing.

**Comment by PineTreePizza** [comment]
> Thinking it over... we use caching in the API. It may affect the live prices. I'll check and let you know if it can be corrected this way.

Awesome, thanks. The prices for me haven't been updating for two days, which is very unfortunate. Hopefully this gets fixed

**Comment by chilango74** [comment]
> > Thinking it over... we use caching in the API. It may affect the live prices. I'll check and let you know if it can be corrected this way.
> 
> Awesome, thanks. The prices for me haven't been updating for two days, which is very unfortunate. Hopefully this gets fixed

Disabled caching for `/api/live_price/` endpoint. It should work better now. Please check.
Te data is renewd within a 1-minute interval. Prices are provided with 15-20 minutes delay.
