### ISSUE TITLE
Add `dividends_annual` property for Portfolio

### ISSUE THREAD

**Issue by chilango74** [mbk-dev/okama#65]
`dividends_annual` property [exists](https://github.com/mbk-dev/okama/blob/90e25cb4f8f7e93578a2ae33068c7fc0fa291d1d/okama/asset_list.py#L861) in AsssetList. The same should be in Portfolio.

**Comment by JVthearchitect** [comment]
I submitted a commit for this issue. Please let me know if there are any issues. I included the test file that passed.

**Comment by JVthearchitect** [comment]
The pull request is now live.
